# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 <LICENSE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

[package]
name = "safer_cffi"
description = "Building blocks for safer C/Rust interop."
license = "MIT OR Apache-2.0"
repository = "https://github.com/google/safer_cffi"
version = "0.2.0"
edition = "2024"

[dependencies]
libc = "0.2.186"
log = "0.4.33"
allocator_api2 = "0.2"

[dev-dependencies]
googletest = "0.14.3"
